#all:
#	nasm -f elf64 Grace.s -o ASM.o; gcc ASM.o -no-pie -o ASM
#
#clean:
#	rm -rf ASM
#	rm -rf ASM.o
#	rm -rf Grace_kid.s
#


#all:
#	nasm -f elf64 Sully.s -o Sully.o; gcc Sully.o -no-pie -o Sully
#
#clean:
#	rm -rf Sully
#	rm -rf Sully.o
#	rm -rf Sully_4.s
#

all:
	gcc ../C/Sully.c -o Sully